modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "azureframelib"
version = "${version}"
displayName = "AzureFrameLib"
authors = "Azureddraig"
description = '''
Shared library and dynamic resource framework for Minecraft mods.
'''

[[dependencies.azureframelib]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azureframelib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azureframelib]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
